version: "3.9"

services:
  app:
    build: ../book-socialing-app
    container_name: app
    restart: always
    env_file:
      - ../.env
    volumes:
      - ../data:/var/data/saisai-file

  nginx:
    build:
      context: ..
      dockerfile: ./book-socialing-deploy/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh
    command: [ "-c", "while :; do certbot renew --quiet; sleep 12h & wait $${!}; done" ]
