app:
  server-url: ${APP_SERVER_URL:http://localhost:8080}

spring:
  application:
    name: socialing
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "${KAKAO_REST_API_KEY}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "${app.server-url}/login/oauth2/code/kakao"
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: "${JWT_SECRET_KEY}"
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400
